title: Someever's Blog
description: 一个十年IT老兵的日志，“路漫漫其修远兮，吾将上下而求索。”.
show_downloads: true

url: "https://someever.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%Y-%m-%d"

theme: # leave it empty

# social
author: someever
image: /thumbnail-jumbo.png

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
